#
# Workspaces rules
#
    assign [app_id="deezer-desktop"] 10

#
# Windows rules
#
    for_window [app_id="blueman-manager"] floating enable, move position center
    for_window [app_id="pavucontrol"] floating enable, move position center
    for_window [app_id="nm-connection-editor"] floating enable, move position center
